### ISSUE TITLE
wrong time base enumeration class used in ttml2 model

### ISSUE THREAD

**Issue by skynavga** [skynav/ttt#139]
use of ttp:timeBase throws exception when using model ttml2

Exception in thread "main" java.lang.IllegalStateException: Unexpected value of type 'com.skynav.ttv.model.ttml2.ttd.TimeBase
	at com.skynav.ttv.verifier.ttml.parameter.TimeBaseVerifier.verify(TimeBaseVerifier.java:44)
	at com.skynav.ttv.verifier.ttml.TTML1ParameterVerifier$ParameterAccessor.verify(TTML1ParameterVerifier.java:351)
	at com.skynav.ttv.verifier.ttml.TTML1ParameterVerifier.verifyAttributeItems(TTML1ParameterVerifier.java:219)
	at com.skynav.ttv.verifier.ttml.TTML1ParameterVerifier.verify(TTML1ParameterVerifier.java:209)
	at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyTimedTextParameterAttributes(TTML1SemanticsVerifier.java:769)
	at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyTimedText(TTML1SemanticsVerifier.java:144)
	at com.skynav.ttv.verifier.ttml.TTML2SemanticsVerifier.verifyRoot(TTML2SemanticsVerifier.java:72)

**Comment by skynavga** [comment]
Fixed in 2e180d0e41108c44f60c3bdfd74ee1e77242dbd8.
