### ISSUE TITLE
number fraction separator should not be locale specific

### ISSUE THREAD

**Issue by spoeschel** [skynav/ttt#164]
Compiling ttt-ttpe on my system fails during the tests:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.skynav.ttpe.app.PresenterTestCases
Tests run: 85, Failures: 85, Errors: 0, Skipped: 0, Time elapsed: 32.331 sec <<< FAILURE! - in com.skynav.ttpe.app.PresenterTestCases
test019PlacementAndAlignmentDefault(com.skynav.ttpe.app.PresenterTestCases)  Time elapsed: 1.515 sec  <<< FAILURE!
java.lang.AssertionError: Expected attribute value '28.8' but was '28,8' - comparing <g font-size="28.8"...> at /svg[1]/g[1]/svg[1]/g[1]/g[1]/@font-size to <g font-size="28,8"...> at /svg[1]/g[1]/svg[1]/g[1]/g[1]/@font-size
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.skynav.ttpe.app.PresenterTestCases.checkDifferencesXML(PresenterTestCases.java:741)
	at com.skynav.ttpe.app.PresenterTestCases.checkDifferences(PresenterTestCases.java:728)
	at com.skynav.ttpe.app.PresenterTestCases.checkDifferences(PresenterTestCases.java:687)
	at com.skynav.ttpe.app.PresenterTestCases.checkDifferences(PresenterTestCases.java:664)
	at com.skynav.ttpe.app.PresenterTestCases.checkDifferences(PresenterTestCases.java:644)
	at com.skynav.ttpe.app.PresenterTestCases.maybeCheckDifferences(PresenterTestCases.java:623)
	at com.skynav.ttpe.app.PresenterTestCases.performPresentationTest(PresenterTestCases.java:520)
	at com.skynav.ttpe.app.PresenterTestCases.performPresentationTest(PresenterTestCases.java:484)
	at com.skynav.ttpe.app.PresenterTestCases.test019PlacementAndAlignmentDefault(PresenterTestCases.java:150)

[a bunch of similar errors follows...]
```

The reason in this particular case is the `doubleFormatter`in the `/ttt-ttpe/src/main/java/com/skynav/ttpe/render/svg/SVGRenderProcessor.java` which does not specify the to be used Locale. Thus Java falls back to the system Locale, which is the german one, because I have a german system. As Germany uses the comma instead of the point as decial mark, the format conversion returns a wrong result.

When I temporarily set the system locale to english, it works and the tests are passed - but this apporach is of course not very convenient. Thus I suggest to add a regarding Locale to all invoked functions like `MessageFormat` so that ttt-ttpe can be used independent from any system locale.

**Comment by skynavga** [comment]
Addressed in 7db4838cf4558a9fb44da902f7ffe0f48c408cc8.
