### ISSUE TITLE
nested span crash

### ISSUE THREAD

**Issue by mikedo** [skynav/ttt#178]
See document below run with:

java -jar ttt-ttxv-3.0-SNAPSHOT-jar-with-dependencies.jar --model imsc1 nested-span.xml

**Comment by mikedo** [comment]
[nested-span.zip](https://github.com/skynav/ttt/files/661742/nested-span.zip)

**Comment by mikedo** [comment]
Crash backtrace:

C:\Users\Michael\Documents\CEA\R4\IMSC1>java -jar ttt-ttxv-3.0-SNAPSHOT-jar-with-dependencies.jar --model imsc1 nested-span.xml
Timed Text Transforming Verifier (TTXV) [1.0.0dev] Copyright 2013-16 Skynav, Inc.
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: javax.xml.bind.JAXBElement.getBegin()
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.getTimingValue(IMSC1SemanticsVerifier.java:526)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.getBegin(IMSC1SemanticsVerifier.java:496)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.isExplicitlyTimed(IMSC1SemanticsVerifier.java:489)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.isSelfOrAncestorExplicitlyTimed(IMSC1SemanticsVerifier.java:476)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyTimedContent(IMSC1SemanticsVerifier.java:418)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyTimeableContentIsTimed(IMSC1SemanticsVerifier.java:403)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verify(IMSC1SemanticsVerifier.java:118)
        at com.skynav.ttv.app.TimedTextVerifier.verifySemantics(TimedTextVerifier.java:2088)
        at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2122)
        at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2250)
        at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2327)
        at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2293)
        at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:534)
        at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:530)
        at com.skynav.ttxv.app.TimedTextTransformingVerifier.main(TimedTextTransformingVerifier.java:77)
Caused by: java.lang.NoSuchMethodException: javax.xml.bind.JAXBElement.getBegin()
        at java.lang.Class.getMethod(Unknown Source)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.getTimingValue(IMSC1SemanticsVerifier.java:517)
        ... 14 more

**Comment by skynavga** [comment]
It appears that the file ttt-ttxv-3.0-SNAPSHOT-jar-with-dependencies.jar
does not have the correct dependencies, and, in particular, the underlying
TTV dependencies. How/where did you obtain this jar?

**Comment by skynavga** [comment]
Turns out it was a bug after all. Fixed in 3fb629311c57c45e75217097c28f38ee3544451d.
