### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: javax.xml.bind.JAXBElement.getBegin()

### ISSUE THREAD

**Issue by palemieux** [skynav/ttt#182]
`java -jar c:\\bin\\ttxv\\ttt-ttxv-3.0-SNAPSHOT-jar-with-dependencies.jar --model imsc1`

[BasicTiming008.zip](https://github.com/skynav/ttt/files/728301/BasicTiming008.zip)
```
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: javax.xml.bind.JAXBElement.getBegin()
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.getTimingValue(IMSC1SemanticsVerifier.java:526)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.getBegin(IMSC1SemanticsVerifier.java:496)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.isExplicitlyTimed(IMSC1SemanticsVerifier.java:489)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.isSelfOrAncestorExplicitlyTimed(IMSC1SemanticsVerifier.java:476)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyTimedContent(IMSC1SemanticsVerifier.java:418)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verify(IMSC1SemanticsVerifier.java:118)
	at com.skynav.ttv.app.TimedTextVerifier.verifySemantics(TimedTextVerifier.java:2088)
	at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2122)
	at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2250)
	at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2327)
	at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2293)
	at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:534)
	at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:530)
	at com.skynav.ttxv.app.TimedTextTransformingVerifier.main(TimedTextTransformingVerifier.java:77)
Caused by: java.lang.NoSuchMethodException: javax.xml.bind.JAXBElement.getBegin()
	at java.lang.Class.getMethod(Unknown Source)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.getTimingValue(IMSC1SemanticsVerifier.java:517)
```

**Comment by skynavga** [comment]
Fixed in 3fb629311c57c45e75217097c28f38ee3544451d.
