### ISSUE TITLE
Exception at com.skynav.ttv.verifier.imsc.IMSC1StyleVerifier.isLengthUnitsPermitted(IMSC1StyleVerifier.java:91)

### ISSUE THREAD

**Issue by palemieux** [skynav/ttt#183]
[CellResolution001.zip](https://github.com/skynav/ttt/files/728317/CellResolution001.zip)

` java -jar c:\\bin\\ttxv\\ttt-ttxv-3.0-SNAPSHOT-jar-with-dependencies.jar --model imsc1`

```
Exception in thread "main" java.lang.NullPointerException
	at com.skynav.ttv.verifier.imsc.IMSC1StyleVerifier.isLengthUnitsPermitted(IMSC1StyleVerifier.java:91)
	at com.skynav.ttv.verifier.util.Lengths.isUnitsPermitted(Lengths.java:362)
	at com.skynav.ttv.verifier.util.Lengths.isLength(Lengths.java:123)
	at com.skynav.ttv.verifier.util.Lengths.isLengths(Lengths.java:389)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.parseLengthPair(IMSC1SemanticsVerifier.java:343)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyRegionContainment(IMSC1SemanticsVerifier.java:291)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyRegionContainment(IMSC1SemanticsVerifier.java:232)
	at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verify(IMSC1SemanticsVerifier.java:114)
	at com.skynav.ttv.app.TimedTextVerifier.verifySemantics(TimedTextVerifier.java:2088)
	at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2122)
	at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2250)
	at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2327)
	at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2293)
	at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:534)
	at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:530)
	at com.skynav.ttxv.app.TimedTextTransformingVerifier.main(TimedTextTransformingVerifier.java:77)
```

**Comment by skynavga** [comment]
Fixed in 52bfa5bc7795cbd9f65cb7c7921963a5e5d91a3b.
