### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException

### ISSUE THREAD

**Issue by skynavga** [skynav/ttt#185]
As reported by @palemieux.

Exception in thread "main" java.lang.IllegalStateException
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifySMPTEBackgroundImage(IMSC1SemanticsVerifier.java:794)
        at com.skynav.ttv.verifier.smpte.ST20522010SemanticsVerifier.verifySMPTEAttribute(ST20522010SemanticsVerifier.java:339)
        at com.skynav.ttv.verifier.smpte.ST20522010SemanticsVerifier.verifySMPTEOtherAttributes(ST20522010SemanticsVerifier.java:324)
        at com.skynav.ttv.verifier.smpte.ST20522010SemanticsVerifier.verifyOtherAttributes(ST20522010SemanticsVerifier.java:289)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyOtherAttributes(IMSC1SemanticsVerifier.java:775)
        at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyOtherAttributes(TTML1SemanticsVerifier.java:1001)
        at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyDivision(TTML1SemanticsVerifier.java:538)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyDivision(IMSC1SemanticsVerifier.java:600)
        at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyBody(TTML1SemanticsVerifier.java:509)
        at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyTimedText(TTML1SemanticsVerifier.java:341)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verifyTimedText(IMSC1SemanticsVerifier.java:566)
        at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyRoot(TTML1SemanticsVerifier.java:123)
        at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verify(TTML1SemanticsVerifier.java:118)
        at com.skynav.ttv.verifier.imsc.IMSC1SemanticsVerifier.verify(IMSC1SemanticsVerifier.java:102)
        at com.skynav.ttv.app.TimedTextVerifier.verifySemantics(TimedTextVerifier.java:2088)
        at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2122)
        at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2250)
        at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2327)
        at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2293)
        at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:534)
        at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:530)
        at com.skynav.ttxv.app.TimedTextTransformingVerifier.main(TimedTextTransformingVerifier.java:77)

**Comment by skynavga** [comment]
Fixed in 9e509bf1423fb7862b6776b10d3c168bcd08e310.
